# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
r:
  - oldrel
  - release
  - devel
addons:
  apt:
    packages:
      - julia
script:
- R CMD build .
- R CMD check *tar.gz
sudo: false
cache: packages
